version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.2
dependencies:
  pre:
    - npm install -g @angular/cli
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Front-end Build
          command: |
            npm run frontend:build
      - run:
          name: Install Back-End Dependencies
          command: |
            npm run backend:install
      - run:
          name: Back-end Build
          command: |
            npm run backend:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Install Angular CLI Tools
          command: |
            npm install -g @angular/cli
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python-pip python-dev
      - run:
          name: Install AWS dependencies
          command: |
            sudo pip install awsebcli
      - run:
            name: Install Front-End Dependencies
            command: |
              npm run frontend:install
      - run:
            name: Install Back-End Dependencies
            command: |
              npm run backend:install
      - run:
          name: Front-end Build
          command: |
            npm run frontend:build  
      - run:
          name: Back-end Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Front-End
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy
workflows:
  store-app:
    jobs:
      - build
      - deploy:
          requires:
            - build