version: 2.1
orbs:
  #Install the necessary orbs, the aws-elastic-beanstalk orb is a bit iffy
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.2
dependencies:
  #Should give us global access to ng 
  pre:
    - npm install -g @angular/cli
jobs:
  #This job just builds the project and installs dependencies, though it doesn't seem to hold between jobs
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Front-end Build
          command: |
            npm run frontend:build
      - run:
          name: Install Back-End Dependencies
          command: |
            npm run backend:install
      - run:
          name: Back-end Build
          command: |
            npm run backend:build
  #Runs our tests, should be done after a build and install (both will probably fail)
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Test Front-End
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy
  #Deploy our app to amazon s3 & EB
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy
      - run:
        #pass the environment variables from here to elastic beanstalk
          name: Set Environment Variables
          command: |
            sleep 25
            eb setenv AWD_DB_USER=$AWD_DB_USER AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_DB_HOST=$AWS_DB_HOST \
            AWS_DB_NAME=$AWS_DB_NAME AWS_DB_PASSWORD=$AWS_DB_PASSWORD AWS_DB_PORT=$AWS_DB_PORT AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
            AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY BCRYPT_PASSWORD=$BCRYPT_PASSWORD ENV=$ENV SALT_ROUNDS=$SALT_ROUNDS TOKEN_SECRET=$TOKEN_SECRET
      - run:
          name: Deploy Front-End
          command: |
            npm run frontend:deploy
workflows:
  store-app-test:
    jobs:
      - build
      - test:
          requires:
            - build
  store-app:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build